// <auto-generated />
using FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace finalproject.Migrations
{
    [DbContext(typeof(CardDbContext))]
    partial class CardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("FinalProject.Models.BaseballCard", b =>
                {
                    b.Property<int>("BaseballCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardCondition")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardPackage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("BaseballCardID");

                    b.ToTable("BaseballCard");
                });

            modelBuilder.Entity("FinalProject.Models.Owner", b =>
                {
                    b.Property<int>("OwnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseballCardID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ownership")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerID");

                    b.HasIndex("BaseballCardID");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("FinalProject.Models.Owner", b =>
                {
                    b.HasOne("FinalProject.Models.BaseballCard", "BaseballCard")
                        .WithMany("Owners")
                        .HasForeignKey("BaseballCardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseballCard");
                });

            modelBuilder.Entity("FinalProject.Models.BaseballCard", b =>
                {
                    b.Navigation("Owners");
                });
#pragma warning restore 612, 618
        }
    }
}
